---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
  - name: centos-6.5
  - name: ubuntu-12.04
    run_list: apt::default

suites:
  - name: cdh4
    run_list:
      - recipe[hadoop::default]
      - recipe[hadoop::hadoop_hdfs_namenode]
      - recipe[hadoop::hadoop_hdfs_secondarynamenode]
      - recipe[hadoop::hadoop_hdfs_datanode]
      - recipe[hadoop::hadoop_mapreduce_historyserver]
      - recipe[hadoop::hadoop_yarn_resourcemanager]
      - recipe[hadoop::hadoop_yarn_nodemanager]
      - recipe[hadoop::hadoop_yarn_resourcemanager]
      - recipe[hadoop::hbase_master]
      - recipe[hadoop::hbase_regionserver]
      - recipe[hadoop::hbase_rest]
      - recipe[hadoop::hbase_thrift]
      - recipe[hadoop::hive_metastore]
      - recipe[hadoop::hive_server]
      - recipe[hadoop::hive_server2]
      - recipe[hadoop::oozie]
      - recipe[hadoop::oozie_client]
      - recipe[hadoop::pig]
      - recipe[hadoop::zookeeper]
      - recipe[hadoop::zookeeper_server]
      - recipe[minitest-handler::default]
    attributes: { hadoop: { distribution: 'cdh', distribution_version: 4 } }
  - name: cdh5
    run_list:
      - recipe[hadoop::default]
      - recipe[hadoop::hadoop_hdfs_namenode]
      - recipe[hadoop::hadoop_hdfs_secondarynamenode]
      - recipe[hadoop::hadoop_hdfs_datanode]
      - recipe[hadoop::hadoop_mapreduce_historyserver]
      - recipe[hadoop::hadoop_yarn_resourcemanager]
      - recipe[hadoop::hadoop_yarn_nodemanager]
      - recipe[hadoop::hadoop_yarn_resourcemanager]
      - recipe[hadoop::hbase_master]
      - recipe[hadoop::hbase_regionserver]
      - recipe[hadoop::hbase_rest]
      - recipe[hadoop::hbase_thrift]
      - recipe[hadoop::hive_metastore]
      - recipe[hadoop::hive_server]
      - recipe[hadoop::hive_server2]
      - recipe[hadoop::oozie]
      - recipe[hadoop::oozie_client]
      - recipe[hadoop::pig]
      - recipe[hadoop::zookeeper]
      - recipe[hadoop::zookeeper_server]
      - recipe[minitest-handler::default]
    attributes: { hadoop: { distribution: 'cdh', distribution_version: 5 } }
  - name: hdp20
    run_list:
      - recipe[hadoop::default]
      - recipe[hadoop::hadoop_hdfs_namenode]
      - recipe[hadoop::hadoop_hdfs_secondarynamenode]
      - recipe[hadoop::hadoop_hdfs_datanode]
      - recipe[hadoop::hadoop_mapreduce_historyserver]
      - recipe[hadoop::hadoop_yarn_resourcemanager]
      - recipe[hadoop::hadoop_yarn_nodemanager]
      - recipe[hadoop::hadoop_yarn_resourcemanager]
      - recipe[hadoop::hbase_master]
      - recipe[hadoop::hbase_regionserver]
      - recipe[hadoop::hbase_rest]
      - recipe[hadoop::hbase_thrift]
      - recipe[hadoop::hive_metastore]
      - recipe[hadoop::hive_server]
      - recipe[hadoop::hive_server2]
      - recipe[hadoop::oozie]
      - recipe[hadoop::oozie_client]
      - recipe[hadoop::pig]
      - recipe[hadoop::zookeeper]
      - recipe[hadoop::zookeeper_server]
      - recipe[minitest-handler::default]
    attributes: { hadoop: { distribution: 'hdp', distribution_version: '2.0' } }
  - name: hdp21
    run_list:
      - recipe[hadoop::default]
      - recipe[hadoop::hadoop_hdfs_namenode]
      - recipe[hadoop::hadoop_hdfs_secondarynamenode]
      - recipe[hadoop::hadoop_hdfs_datanode]
      - recipe[hadoop::hadoop_mapreduce_historyserver]
      - recipe[hadoop::hadoop_yarn_resourcemanager]
      - recipe[hadoop::hadoop_yarn_nodemanager]
      - recipe[hadoop::hadoop_yarn_resourcemanager]
      - recipe[hadoop::hbase_master]
      - recipe[hadoop::hbase_regionserver]
      - recipe[hadoop::hbase_rest]
      - recipe[hadoop::hbase_thrift]
      - recipe[hadoop::hive_metastore]
      - recipe[hadoop::hive_server]
      - recipe[hadoop::hive_server2]
      - recipe[hadoop::oozie]
      - recipe[hadoop::oozie_client]
      - recipe[hadoop::pig]
      - recipe[hadoop::zookeeper]
      - recipe[hadoop::zookeeper_server]
      - recipe[minitest-handler::default]
    attributes: { hadoop: { distribution: 'hdp', distribution_version: '2.1' } }
